### PR TITLE
In case of unicode response the content length header is not matching actual body length (because of the multibyte size diference)

### PR DESCRIPTION
**Pull request by kraz**
Added options capabilities
Added the ability to set characterset
Added the option wather the unicode characters in the response must be
ASCII encoded (RFC 4627 - IETF)

### CODE REVIEW

**Comment by longlho** [comment]
Can you add some unit tests for this? After that I'd be happy to merge.

**Comment by longlho** [comment]
Also ignore the buildhive stuff :)

**Comment by kraz** [comment]
I had to modify the test suite a little bit so it can support an options parameter. Of course it might not be the best way to do it, but i didn't want to change the basic logic. I wanted to apply the options set to the basic tests (so they can be executed against diferent set of options, like charset and encode unicode chars to ASCII). I also have to note that the current version of node.js is not handling properly the diferences in content-length and actual body of the http protocol, as noteted in these reported issues:

https://github.com/joyent/node/issues/3354
https://github.com/joyent/node/issues/3375

**Comment by longlho** [comment]
Cool thanks I'll look into merging this :)

**Comment by longlho** [comment]
Merged and made some changes. Thanks a lot! Great work :)

**Comment by kraz** [comment]
:) Nice, looks better after your changes. Thanks!

**Pull request merged**
